### PR TITLE
r-rtracklayer: deprecate R <= 4.1 versions, dependency cleanup, add conflicts

### PR DESCRIPTION
**Pull request by w8jcik**
# Build grid

image

### CODE REVIEW

File: repos/spack_repo/builtin/packages/r_rtracklayer/package.py [hunk 1]
```diff
@@ -20,59 +20,93 @@ class RRtracklayer(RPackage):
...
+    depends_on("r-genomicranges@1.37.2:", type=("build", "run"), when="@1.50.0:")
+    depends_on("r-genomicranges@1.21.20:", type=("build", "run"))
+
+    depends_on("r-httr", type=("build", "run"), when="@1.64.0:")
+
+    depends_on("r-iranges@2.13.13:", type=("build", "run"), when="@1.40.6:")
+    depends_on("r-iranges@2.11.12:", type=("build", "run"), when="@1.38.3:")
+    depends_on("r-iranges@2.3.7:", type=("build", "run"))
+
     depends_on("r-restfulr@0.0.13:", type=("build", "run"), when="@1.54.0:")
```
Comment (bernhardkaindl) [inline repos/spack_repo/builtin/packages/r_rtracklayer/package.py:78]: @w8jcik, Incredible work!

JFYI, through `restfulr`, also the new versions depend indirectly on `r-curl`, which isn't updated for with 4.6.1, so to build with 4.6.1, I needed
```py
$ spack checksum -a -b -l r-rcurl
-> version("1.98-1.19", sha256="57300322f0da21deef5094f12b4a7a94834e60262859e5afb5ff16ac7d431205")
```
BTW, rcurl is a dependency of 14 recipes:
```py
$ git grep -l depends_on..r-rcurl|wc -l
14
$ git grep -l depends_on..r-rcurl|cut -d/ -f5
r_affycompatible
r_annotate
r_annotationforge
r_biomart
r_biomartr
r_fds
r_genomeinfodb
r_genomicfeatures
r_geoquery
r_kegggraph
r_paleotree
r_restfulr
r_rtracklayer
r_spatialeco
```

**Review by bernhardkaindl — DISMISSED** [review]

File: repos/spack_repo/builtin/packages/r_rtracklayer/package.py [hunk 2]
```diff
@@ -20,59 +20,93 @@ class RRtracklayer(RPackage):
...
         version("1.50.0", commit="d2e61f72ff5d5a94c2c487ba108a37f23bfcc1e6")
         version("1.44.4", commit="aec96e85daf53b5c5eb2e89250d2755352be4de3")
         version("1.42.2", commit="76702f671faea736807d54aeecfbadcd152d94c5")
         version("1.40.6", commit="ba9a6e711504a702147383bc7abfcc36eb304df7")
         version("1.38.3", commit="f20db703c09dc7e808c09e9b78c15aec9e546248")
         version("1.36.6", commit="8c0ac7230f94e0c5a981acbb178c8de70e968131")
 
-    depends_on("c", type="build")  # generated
+    # # > chain_io.c:1:10: fatal error: S.h: No such file or directory
+    # conflicts("r@4.2:", when="@:1.54")
```
[the remark this answers is not in the document]
Comment (bernhardkaindl) [reply repos/spack_repo/builtin/packages/r_rtracklayer/package.py]: While a deprecation used for these versions too, the conflicts would likely still be good.

@w8jcik, I'll enable auto-merge, so if you want to merge without any changes, you only need to set both open conversations to resolved.

This should cause that Auto-merge will immediately merge when all conversations are resolved.

[the remark this answers is not in the document]
Comment (w8jcik) [reply repos/spack_repo/builtin/packages/r_rtracklayer/package.py]: I believe that Spack CI will reject this Pull Request if I add the conflict, this is why it was disabled, but we can check.

File: repos/spack_repo/builtin/packages/r_rtracklayer/package.py (hunk 1 above)
Comment (w8jcik) [reply repos/spack_repo/builtin/packages/r_rtracklayer/package.py:78]: Thanks =)

I didn't notice the issue because `r-rcurl` builds, it is just bound by GCC <= 13.   
I think I had it already installed and Spack picked it up during resolution.

image

It's true that it will fail on fresh Spack installation.

File: repos/spack_repo/builtin/packages/r_rtracklayer/package.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (w8jcik) [reply repos/spack_repo/builtin/packages/r_rtracklayer/package.py]: All good. CI was protesting before the deprecations were added.

File: repos/spack_repo/builtin/packages/r_rtracklayer/package.py (hunk 1 above)
Comment (w8jcik) [reply repos/spack_repo/builtin/packages/r_rtracklayer/package.py:78]: This should fix it https://github.com/spack/spack-packages/pull/6111

**Review by bernhardkaindl — APPROVED** [review]
