### PR TITLE
Revert "cuda: add v13.1.2, v13.2.0, v13.2.1 and v13.3.0"

### PR DESCRIPTION
**Pull request by sethrj**
Reverts spack/spack-packages#4897 : downstream packages including strumpack seem to fail with it; they weren't tested on gitlab CI due to an error introduced by https://github.com/spack/spack-packages/pull/4615 and fixed in #5046.

Draft to test whether the pipeline passes with the reversion.

### CODE REVIEW

**Comment by rbberger** [comment]
@sethrj instead of reverting, you should document which ones are failing for you and add conflicts.

**Comment by sethrj** [comment]
This unfortunately is due to a lapse in the CI system; it's the responsibility of each PR to make sure that new capabilities don't break other code. I'm mostly trying to verify that the CI works after this; a couple of software packages have been broken on develop since #4897 .

https://gitlab.spack.io/spack/spack-packages/-/pipelines/1623929

**Comment by alalazo** [comment]
@sethrj Use the `don't merge yet` label and make this a normal PR. Pipelines don't run on draft PRs :grimacing:

**Comment by balay** [comment]
https://gitlab.spack.io/spack/spack-packages/-/jobs/22451976
```
/tmp/root/spack-stage/spack-stage-petsc-3.25.1-lxmyy25uscljmm3jlejoth6zcia3lveg/spack-src/src/mat/impls/diagonal/cupm/cuda/../matdiagonalcupm.hpp(43): error: namespace "thrust" has no member "tuple"
    using argument_type = thrust::tuple<PetscScalar, PetscScalar, PetscScalar>;
```
FWIW cuda@13.3 build issue is fixed in petsc@3.25.2 - that got similarly merged to develop via

https://github.com/spack/spack-packages/pull/5053

**Comment by balay** [comment]
> @sethrj Use the don't merge yet label and make this a normal PR. Pipelines don't run on draft PRs 😬

The label can be easily ignored [I've had that issue once].

 Would be nice if the restriction on draft PRs can be removed [or  be able to add in CI via a lablel - or other mechanisms]

**Comment by balay** [comment]
Is it worth checking if just reverting cuda-13.3 (or making cuda-13.2.1 the default) would work - without a full revert?

**Comment by balay** [comment]
And I  see tau, strumpack have PRs related to cuda-13.2+ merged in (along with petsc).

Likely outstanding pkgs [from the above pipeline failure]:
- visit
- omega-h

**Comment by balay** [comment]
And both visit and omega-h failures appear unrelated to cuda-13.2
- https://gitlab.spack.io/spack/spack-packages/-/jobs/22456141/viewer
- https://gitlab.spack.io/spack/spack-packages/-/jobs/22452092/viewer

**Review by rbberger — CHANGES_REQUESTED** [review]
Revert seems overkill at this point.
