### PR TITLE
libiconv: Fix build error with Intel Classic compilers

### PR DESCRIPTION
**Pull request by nboelte**
This fixes the following build error with the intel-oneapi-compilers-classic:

```
> malloca.c(49): error #3895: expected a comma (the one-argument version of static_assert is not enabled in this mode)
    static_assert (2 * sa_alignment_max - 1 <= (small_t) -1);
```

PS: The same problem also affects libidn2 and gettext, i'll open a PR for those later when this one is accepted and i have time

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
Tested that this didn't break gcc build on Ubuntu 24.04, LGTM.

**Comment by bernhardkaindl** [comment]
@nboelte, CI failed and might need a rebase onto the latest develop branch.

@nboelte, Normally, maintainers can trigger the rebase to develop, but it appears write permission is disabled for maintainers, at least GitHub does not offer to do the rebase to me at the moment.

**Comment by nboelte** [comment]
I clicked the "Sync Fork" button on the feature branch, maybe it works now?
